name: MyAMP
description: Custom Baseline AMP
author: Joe Montenaro
specification_version: 1.0
prototype_version: 1.0.5

runtimes:
  - editor: Workbench
    kernel: Python 3.7
    edition: Standard

environment_variables:
  GIT_REPO_URL:
    default: ""
    description: "Target repo URL"

tasks:
- type: run_session
  name: Set GIT Repo URL
  code: !git remote set-url origin $GIT_REPO_URL
  kernel: python3
  memory: 1
  cpu: 1
  gpu: 0
