name: MyAMP
description: Example AMP with GIT repo configuration
author: Joe Montenaro
specification_version: 1.0
prototype_version: 2.0

environment_variables:
  GIT_REPO_URL:
    default: ""
    description: "Target repo URL"
    required: true

tasks:
- type: run_session
  name: Set GIT Repo URL
  code: |
    !git remote set-url origin $GIT_REPO_URL
  kernel: python3
  memory: 1
  cpu: 1
