name: MyAMP
description: Custom Baseline AMP
author: Joe Montenaro
specification_version: 1.0
prototype_version: 1.0.2

runtimes:
  - editor: Workbench
    kernel: Python 3.7
    edition: Standard

environment_variables:
  GIT_REPO_URL:
    default: ""
    description: "Target repo URL"

tasks:
- type: run_session
  name: Set GIT Repo URL
  script: utils/set_git_repo_url.py
  kernel: python3
  memory: 1
  cpu: 1
  gpu: 0
